### PR TITLE
Get the validation messages before the closure

### LINKED ISSUE #45: Argument 4 passed to Cviebrock\ImageValidator\ImageValidator::__construct() must be of the type array
Hello,

I've been getting this error since a recent update.

``` php
Type error: Argument 4 passed to Cviebrock\ImageValidator\ImageValidator::__construct() must be of the type array, string given, called in /home/vagrant/monitoring-assistance/vendor/cviebrock/image-validator/src/ImageValidatorServiceProvider.php on line 34
```

This error is fixed by not type hinting for an array as the forth argument. This issue from what I could debug is that the translations aren't loaded, and thus the key is sent to the constructor.

### PR DESCRIPTION
**Pull request by nWidart**
Fixes #45

### CODE REVIEW

**Comment by cviebrock** [comment]
Thanks!

**Comment by nWidart** [comment]
Awesome, thanks for the tag! 😄 

If you could give a heads up here when you did, so I can update composer that's be nice :).

**Comment by cviebrock** [comment]
Version 2.1.1 was just pushed.  Packagist should pick it up shortly.

**Comment by nWidart** [comment]
cool thanks. 👍

**Pull request merged**
