### PR TITLE
fix italian language

### PR DESCRIPTION
**Pull request by neomusic**
My pull request fix italian translation for laravel 5.2
**Thank you!**

### CODE REVIEW

**Comment by cviebrock** [comment]
Grazie!

**Comment by cviebrock** [comment]
I think you must have forked from an older version.  That correction to the Italian translation is already in place in the 2.2.2 tag.

**Comment by neomusic** [comment]
Yes. Because the 2.2.2 tag in not compatible with laravel 5.2

**Comment by cviebrock** [comment]
Hmm .. then your PR should probably not have made against the master branch.

That said, you don't need this package any more:

> As of Laravel version 5.2, there are now built-in validation rules for image dimensions and aspect ratios. This package is not required and will no longer be maintained.

**Pull request closed without merging**
