### PR TITLE
I've added Russian localization

### PR DESCRIPTION
**Pull request by DexinDev**
It wont be superfluous :)

### CODE REVIEW

**Comment by cviebrock** [comment]
I don't speak Russian ... but are you basically just changing _px_ to _pixel(s)_ in those strings?

**Comment by DexinDev** [comment]
There is two commits

**Comment by cviebrock** [comment]
Yes, but I'm trying to figure out what the overall purpose of the change is.

**Comment by DexinDev** [comment]
I've added the catalog "RU" and "validation.php" file with the Russian localization. After I've corrected some of the words.

**Comment by cviebrock** [comment]
Thanks!

**Comment by DexinDev** [comment]
You are welcome :)

**Pull request merged**
